#!/bin/bash

set -euo pipefail
THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function run_cmd(){
    local cmd=$1
    shift || true
    (
        "cmd_$cmd" "$@"
    )
}

function help(){
cat <<EOT
       Run commands for "$THISDIR"

           lint:             Run R and C++ linters
           check:            Run R CMD check on the package
           full_lint         Run C++ linter with information and headers

EOT
}

function main(){
    cmd=${1-default}
    shift || true
    case "$cmd" in
        help)
            help "$cmd"
            ;;
        lint|check|full_lint|default)
            run_cmd "$cmd" "$@"
            ;;
         *)
            echo "No-op $cmd"
            ;;
    esac
}

function cmd_lint(){
    Rscript -e 'lintr::lint_package()'
    cppcheck src/  --language=c++ --enable=warning,performance,portability,unusedFunction
}


function cmd_check(){
    cd ..
    R CMD check cppRouting/
}

function cmd_full_lint(){
    cppcheck src/ -I "$HOME/R/x86_64-pc-linux-gnu-library/3.6/testthat/include" -I "$HOME/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" --language=c++ --enable=warning,performance,portability,information,unusedFunction,missingInclude
    }

function cmd_default(){
    run_cmd lint "$@"
    run_cmd check "$@"
}

main "$@"
