#' Compute shortest path between origin and destination nodes.
#' 
#' @param Graph  An object generated by cppRouting::makegraph() function.
#' @param from A vector of one or more vertices from which shortest paths are calculated (origin).
#' @param to A vector of one or more vertices (destination).
#' @param algorithm character. "Dijkstra" or "A*"
#' @param constant numeric. Constant to maintain the heuristic function admissible. 
#'Default to 1, when cost is expressed in the same unit than coordinates. See details
#' @return List containing shortest path between from[i] and to[i].
#' @note 'from' and 'to' must be the same length.
#' @details To perform A*, projected coordinates should be provided in the Graph object.  
#' To understand how A star algorithm work, see https://en.wikipedia.org/wiki/A*_search_algorithm .  
#' To understand the importance of constant parameter, see the package description : https://github.com/vlarmet/cppRouting .
#'
#' 
#'
get_path_pair<-function(Graph,from,to,algorithm="Dijkstra",constant=1){
  
  if (length(from)!=length(to)) stop("From and to have not the same length")
  
  if (any(is.na(cbind(from,to)))) stop("NAs are not allowed in origin/destination nodes")
  from<-as.character(from)
  from_id<-Graph$dict$id[match(from,Graph$dict$ref)]
  to<-as.character(to)
  to_id<-Graph$dict$id[match(to,Graph$dict$ref)]
  
  
  if (!is.null(Graph$coords)){
    if (algorithm=="A*"){
      message("Running A* ...")
      res<-Astar_paths(Graph$data$from,Graph$data$to,Graph$data$dist,Graph$nbnode,from_id,to_id,Graph$coords[,2],Graph$coords[,3],constant,Graph$dict$ref)
    }
    else {
      message("Running Dijkstra ...")
      res<-Dijkstra_early_stop_path(Graph$data$from,Graph$data$to,Graph$data$dist,Graph$nbnode,from_id,to_id,Graph$dict$ref)
      
    }
    
  }
  else {
    message("Running Dijkstra ...")
    res<-Dijkstra_early_stop_path(Graph$data$from,Graph$data$to,Graph$data$dist,Graph$nbnode,from_id,to_id,Graph$dict$ref)
    
  }
  
  
  names(res)<-paste0(from,"_",to)
  return(res)
  
  
}
