#' Compute isochrones/isodistances from nodes.
#' 
#' @param Graph  An object generated by cppRouting::makegraph() function.
#' @param from numeric or character. A vector of one or more vertices from which isochrones/isodistances are calculated.
#' @param lim numeric. A vector of one or multiple breaks.
#' @param setdif logical. If TRUE and length(lim)>1, nodes that are reachable in a given break will not appear in a greater one.
#' @return List containing reachable nodes below cost limit(s).
#' @note get_isochrone() recursively perform Dijkstra algorithm for each 'from' nodes and stop when cost limit is reached. 
#' @details If length(lim)>1, value is a list of length(from), containing lists of length(lim)
#' 
#'
get_isochrone<-function(Graph,from,lim,setdif=FALSE){
  
  
  if (any(is.na(from))) stop("NAs are not allowed in origin nodes")
  from<-as.character(from)
  if (sum(from %in% Graph$dict$ref)<length(from)) stop("Some nodes are not in the graph")
  from_id<-Graph$dict$id[match(from,Graph$dict$ref)]
  lim<-as.numeric(lim)
  if (any(is.na(lim))) stop("NAs are not allowed in cost value(s)")
  
  if (length(lim)>1){
    lim<-sort(lim)
    maxlim<-max(lim)
    res<-Isochrone_multi(Graph$data$from,Graph$data$to,Graph$data$dist,Graph$nbnode,from_id,lim,maxlim,setdif,Graph$dict$ref)
    for (i in 1:length(res)) names(res[[i]])<-as.character(lim)
  }
  else {
    res<-Isochrone(Graph$data$from,Graph$data$to,Graph$data$dist,Graph$nbnode,from_id,lim,Graph$dict$ref)
    
  }
  
  names(res)<-from
  
  return(res)
}
