# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Astar <- function(dep, arr, gfrom, gto, gw, NbNodes, lat, lon, k) {
    .Call(`_cppRouting_Astar`, dep, arr, gfrom, gto, gw, NbNodes, lat, lon, k)
}

Astar_paths <- function(gfrom, gto, gw, NbNodes, dep, arr, lat, lon, k, dict) {
    .Call(`_cppRouting_Astar_paths`, gfrom, gto, gw, NbNodes, dep, arr, lat, lon, k, dict)
}

Dijkstra_early_stop <- function(dep, arr, gfrom, gto, gw, NbNodes) {
    .Call(`_cppRouting_Dijkstra_early_stop`, dep, arr, gfrom, gto, gw, NbNodes)
}

Dijkstra_early_stop_path <- function(gfrom, gto, gw, NbNodes, dep, arr, dict) {
    .Call(`_cppRouting_Dijkstra_early_stop_path`, gfrom, gto, gw, NbNodes, dep, arr, dict)
}

Dijkstra_mat <- function(gfrom, gto, gw, NbNodes, dep, arr) {
    .Call(`_cppRouting_Dijkstra_mat`, gfrom, gto, gw, NbNodes, dep, arr)
}

Dijkstra_multi_path <- function(gfrom, gto, gw, NbNodes, dep, arr, dict) {
    .Call(`_cppRouting_Dijkstra_multi_path`, gfrom, gto, gw, NbNodes, dep, arr, dict)
}

Isochrone <- function(gfrom, gto, gw, NbNodes, dep, max_limit, dict) {
    .Call(`_cppRouting_Isochrone`, gfrom, gto, gw, NbNodes, dep, max_limit, dict)
}

Isochrone_multi <- function(gfrom, gto, gw, NbNodes, dep, limit_vec, max_limit, setdif, dict) {
    .Call(`_cppRouting_Isochrone_multi`, gfrom, gto, gw, NbNodes, dep, limit_vec, max_limit, setdif, dict)
}

Astar_par <- function(dep, arr, gfrom, gto, gw, NbNodes, lat, lon, k) {
    .Call(`_cppRouting_Astar_par`, dep, arr, gfrom, gto, gw, NbNodes, lat, lon, k)
}

Dijkstra_early_stop_par <- function(dep, arr, gfrom, gto, gw, NbNodes) {
    .Call(`_cppRouting_Dijkstra_early_stop_par`, dep, arr, gfrom, gto, gw, NbNodes)
}

Dijkstra_mat_par <- function(gfrom, gto, gw, NbNodes, dep, arr) {
    .Call(`_cppRouting_Dijkstra_mat_par`, gfrom, gto, gw, NbNodes, dep, arr)
}

